---

- name: LLAMASWAP
  become: true
  tags:
    - llamaswap
    - llm
  when: llamaswap_active
  block:

    - name: LLAMASWAP check llama-swap
      ansible.builtin.command:
        cmd: llama-swap --version
      changed_when: false
      ignore_errors: true
      register: _llamaswap_status

    - name: LLAMASWAP install llama-swap
      ansible.builtin.unarchive:
        src: "https://github.com/mostlygeek/llama-swap/releases/download/v{{ llamaswap_version }}/llama-swap_{{ llamaswap_version }}_linux_amd64.tar.gz"
        dest: /usr/local/bin
        remote_src: true
        include:
          - llama-swap
        owner: root
        group: root
        mode: "0755"
      notify: LLAMASWAP restart
      when: (_llamaswap_status.rc != 0) or
            (llamaswap_version not in _llamaswap_status.stdout)

    - name: LLAMASWAP sha256sum llama-swap
      ansible.builtin.stat:
        path: /usr/local/bin/llama-swap
        checksum_algorithm: sha256
      register: _llamaswap_binary
      when: (_llamaswap_status.rc != 0) or
            (llamaswap_version not in _llamaswap_status.stdout)

    - name: LLAMASWAP verify llama-swap
      ansible.builtin.assert:
        that:
          - _llamaswap_binary.stat.exists
          - _llamaswap_binary.stat.checksum == llamaswap_checksum_sha256
        fail_msg: "Checksum mismatch or file does not exist!"
        success_msg: "SHA256 checksum verified successfully."
      when: (_llamaswap_status.rc != 0) or
            (llamaswap_version not in _llamaswap_status.stdout)

    - name: LLAMASWAP configure `/etc/llama-swap`
      ansible.builtin.file:
        path: /etc/llama-swap
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: LLAMASWAP configure `/etc/llama-swap/config.yaml`
      ansible.builtin.template:
        src: "{{ role_path }}/templates/config.yaml.j2"
        dest: /etc/llama-swap/config.yaml
        owner: root
        group: root
        mode: "0644"

    - name: LLAMASWAP configure `/etc/systemd/system/llama-swap.service`
      ansible.builtin.template:
        src: "{{ role_path }}/templates/llama-swap.service.j2"
        dest: /etc/systemd/system/llama-swap.service
        owner: root
        group: root
        mode: "0644"
      notify: LLAMASWAP restart

    - name: LLAMASWAP enable service
      ansible.builtin.systemd_service:
        name: llama-swap.service
        state: started
        enabled: true
        daemon_reload: true

